Non wddm enumeration fix2
KhronosGroup/OpenCL-ICD-Loader pull request #178
Opened 2022-05-26 04:57 UTC by nikhiljnv

Always try HKR enumeration irrespective of
DXGK enumeration status.
Currently, we fallback to HKR enumeration
only if DXGK enumeration fails.
For platforms with non-WDDM devices,
DXGK fails to see WDDM adapters.
If one platform with WDDM adapters is enumerated
successfully via DXGK, the other platform with
no WDDM adapters fails to get enumerated.
Using HKR path unconditionally allows such
platforms to be enumerated.

While at it, also fix memory leak due to
not freeing library handle in some cases.

2022-05-27 15:31 UTC, bashbaug approved these changes
Mostly LGTM, had one minor comment that is fine to address later.

2022-05-27 15:33 UTC, bashbaug commented
Should we also bump the OPENCL_ICD_LOADER_VERSION_REV to make it easier to identify ICD loaders with this change?

2022-06-07 09:25 UTC, nikhiljnv commented
@bashbaug ,
Have updated the change with status checks fixed and ICD loader version bumped.
Let me know if this is good to get merged.

2022-06-07 17:41 UTC, bashbaug requested changes

2022-06-09 09:56 UTC, nikhiljnv commented on loader/windows/icd_windows.c
> +    status = khrIcdOsVendorsEnumerateAppPackage();
I have added separate var to track individual status and retained original status logic. Moving KHR_ICD_TRACE to individual function would require handling multiple return points (or at least move them to a single place).

2022-06-09 16:53 UTC, bashbaug approved these changes
Latest version LGTM - thanks!

2022-06-14 15:55 UTC, bashbaug commented
Merging as agreed in the June 14th teleconference.

2022-06-14 15:55 UTC, merged